# Generated by Django 3.2.19 on 2023-05-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
