# Generated by Django 3.2.19 on 2023-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_alter_language_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=25),
        ),
    ]
