# Generated by Django 3.2.19 on 2023-06-14 13:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='../images/profileImages/default-profile-img.jpeg', force_format='JPEG', keep_meta=False, quality=90, scale=None, size=[150, 150], upload_to='images/profileImages/'),
        ),
    ]
