# Generated by Django 3.2.19 on 2023-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
