# Generated by Django 3.2.19 on 2023-06-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='github_link',
        ),
    ]
