# Generated by Django 3.2.19 on 2023-06-20 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_article_primary_language'),
        ('recommended', '0003_auto_20230619_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendedarticle',
            unique_together={('article', 'recommended_to', 'recommended_by')},
        ),
    ]
