# Generated by Django 3.2.19 on 2023-06-20 15:19

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_article_primary_language'),
        ('recommended', '0004_alter_recommendedarticle_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedarticle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='recommendedarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recommendedarticle',
            unique_together={('article', 'recommended_to')},
        ),
    ]
