# Generated by Django 3.2.19 on 2023-06-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_github_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links_article', to='articles.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='link_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
